apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fabflix
  template:
    metadata:
      labels:
        app: fabflix
    spec:
      containers:
        - name: fabflix-container
          image: aashiryarai/fabflix:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: fabflix-service
spec:
  selector:
    app: fabflix
  ports:
    - name: http
      port: 8080
  type: ClusterIP
